# Generated by Django 4.0.4 on 2022-04-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Private_transaciton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('add', models.CharField(max_length=100)),
                ('sectors', models.CharField(max_length=20, null=True)),
                ('floor', models.CharField(max_length=10, null=True)),
                ('acreage', models.CharField(max_length=10, null=True)),
                ('deposit', models.CharField(max_length=20, null=True)),
                ('rent', models.CharField(max_length=20, null=True)),
                ('premium', models.CharField(max_length=20, null=True)),
                ('total_price', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('staff', models.CharField(max_length=20, null=True)),
                ('tel', models.IntegerField(null=True)),
                ('content', models.TextField()),
                ('review_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('good_review', models.TextField(null=True)),
                ('bad_review', models.TextField(null=True)),
                ('want_review', models.TextField(null=True)),
                ('view', models.IntegerField()),
                ('review_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('location', models.TextField()),
                ('scale', models.CharField(max_length=20)),
                ('inquiry', models.TextField()),
                ('tel', models.IntegerField(null=True)),
                ('Announcement_date', models.DateField()),
                ('receipt_date', models.DateField()),
                ('release_date', models.DateField()),
                ('contract_date', models.DateField()),
                ('local', models.DateField()),
                ('etc', models.DateField()),
                ('Reception_place', models.CharField(max_length=10)),
                ('division', models.CharField(max_length=10)),
                ('acreage', models.CharField(max_length=10, null=True)),
                ('supply_area', models.DecimalField(decimal_places=2, max_digits=3)),
                ('supply_normal', models.IntegerField()),
                ('supply_special', models.IntegerField()),
                ('supply_total', models.IntegerField()),
                ('price', models.CharField(max_length=20, null=True)),
                ('views', models.IntegerField()),
            ],
        ),
    ]
