# Generated by Django 4.0.4 on 2022-05-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, null=True)),
                ('location', models.TextField(null=True)),
                ('scale', models.CharField(max_length=20)),
                ('inquiry', models.TextField(null=True)),
                ('tel', models.IntegerField(null=True)),
                ('Announcement_date', models.DateField(null=True)),
                ('receipt_date', models.DateField(null=True)),
                ('release_date', models.DateField(null=True)),
                ('contract_date', models.DateField(null=True)),
                ('local', models.DateField(null=True)),
                ('etc', models.DateField(null=True)),
                ('Reception_place', models.CharField(max_length=10, null=True)),
                ('division', models.CharField(max_length=10, null=True)),
                ('acreage', models.CharField(max_length=10, null=True)),
                ('supply_area', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('supply_normal', models.IntegerField(null=True)),
                ('supply_special', models.IntegerField(null=True)),
                ('supply_total', models.IntegerField(null=True)),
                ('price', models.CharField(max_length=20, null=True)),
                ('views', models.IntegerField(null=True)),
                ('date_start', models.DateField(null=True)),
                ('date_finish', models.DateField(null=True)),
                ('size_one', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('size_two', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('price_one', models.CharField(max_length=20, null=True)),
                ('price_two', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
