# Generated by Django 3.2.13 on 2022-05-09 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Private_transaciton',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
